import { store } from "@risingstack/react-easy-state";

const globalState = store({
  cardHeight: 0,
  checkRequiredQuestionsComplete: false,
  columnWidth: 100,
  currentPage: "landing",
  dataLoaded: false,
  defaultCardFontSize: 15,
  disableRefreshCheck: false,
  displayAccessCodeWarning: false,
  displayContinueButton: false,
  displayLandingContent: false,
  displayNextButton: false,
  displayPartIdWarning: false,
  displayLocalPartIdWarning1: false,
  displayLocalPartIdWarning2: false,
  displaySubmitFallback: false,
  displayGoodbyeMessage: false,
  hasOverloadedColumn: false,
  isLoggedIn: false,
  localParticipantName: "",
  localUsercode: "",
  localStoredQsorts: {},
  overloadedColumn: "",
  partId: "anonymous",
  presortPosCards: [],
  presortNeuCards: [],
  presortNegCards: [],
  presortCards: [],
  presortSortedStatements: 0,
  presortFinished: false,
  progressScore: 10,
  progressScoreAdditional: 0,
  progressScoreAdditionalSort: 0,
  rating2State: {},
  requiredAnswersObj: {},
  results: {},
  resultsPostsort: {},
  resultsSurvey: {},
  sortFinished: false,
  sortFinishedModalHasBeenShown: false,
  sortGridResults: {},
  statementCommentsObj: {},
  submitFailNumber: 0,
  triggerLandingModal: false,
  triggerLocalDeleteModal: false,
  triggerPresortModal: true,
  triggerPresortPreventNavModal: false,
  triggerPresortFinishedModal: false,
  triggerSortModal: true,
  triggerPostsortModal: true,
  triggerSortingFinishedModal: false,
  triggerSortPreventNavModal: false,
  triggerSortOverloadedColumnModal: false,
  triggerSurveyModal: true,
  triggerSurveyPreventNavModal: false,
  triggerTransmissionOKModal: false,
  triggerTransmissionFailModal: false,
  usercode: "no usercode set",
  userInputPartId: "",
  userInputAccessCode: "",
});

export default globalState;
